import { Challenge } from "@/types";

export const CHALLENGES: Challenge[] = [
  {
    position: 0,
    id: "flip-the-coin",
    title: "Flip The Coin",
    difficulty: "Junior",
    status: "done", 
    tags: ["Next.js", "TypeScript", "Tailwind CSS", "Framer Motion"],
    description: "Fizik tabanlı animasyonlar ve asenkron state yönetimi ile kurgulanmış interaktif yazı-tura deneyimi.",
    slug: "flip-the-coin",
  },
  {
    position: 1,
    id: "qr-code-generator",
    title: "QR Code Generator",
    difficulty: "Junior",
    status: "done",
    tags: ["Next.js", "TypeScript", "QR API", "Browser API"],
    description: "URL'leri anlık olarak QR koda dönüştüren, indirme ve paylaşma özelliklerine sahip dinamik araç.",
    slug: "qr-code-generator",
  },
  {
    position: 2,
    id: "device-shop-checkout",
    title: "Device Shop Checkout",
    difficulty: "Junior", 
    status: "done",
    tags: ["Next.js", "Grid", "Forms", "State Management"],
    description: "Apple tarzı şık bir sepet deneyimi. Karmaşık Grid yapıları ve form doğrulama süreçleri üzerine bir çalışma.",
    slug: "device-shop-checkout",
  },
  {
    position: 3,
    id: "github-profile",
    title: "GitHub Profile",
    difficulty: "Mid-Level",
    status: "done",
    tags: ["Next.js", "API Entegrasyonu", "Tailwind CSS"],
    description: "GitHub API kullanarak gerçek zamanlı kullanıcı verisi çeken ve detaylı repo analizi sunan arayüz.",
    slug: "github-profile",
  },
  {
    position: 4,
    id: "pricing-table",
    title: "Pricing Table",
    difficulty: "Junior",
    status: "done",
    tags: ["Next.js", "TypeScript", "Tailwind CSS", "Grid"],
    description: "4 farklı plan seçeneği ve detaylı özellik karşılaştırmaları içeren, tipografi odaklı ve duyarlı bir fiyatlandırma arayüzü.",
    slug: "pricing-table",
  },
  {
  position: 5,
  id: "meet-the-team",
  title: "Meet the Team",
  difficulty: "Junior",
  status: "done",
  tags: ["Next.js", "CSS Grid", "Responsive Design"],
  description: "Asimetrik grid yapıları ve gelişmiş pozisyonlama teknikleri kullanılarak inşa edilmiş, renkli bir ekip tanıtım sayfası.",
  slug: "meet-the-team",
},
{
  position: 6,
  id: "simple-feature-section",
  title: "Simple Feature Section",
  difficulty: "Junior",
  status: "done",
  tags: ["Next.js", "Flexbox", "Responsive"],
  description: "İç içe geçmiş Flexbox yapıları kullanılarak oluşturulan, modern kart tasarımlarına sahip SaaS özellik tanıtım alanı.",
  slug: "simple-feature-section",
},
{
  position: 7,
  id: "simple-article-listing",
  title: "Simple Article Listing",
  difficulty: "Junior",
  status: "done",
  tags: ["Next.js", "Flexbox", "Content Strategy"],
  description: "Metin hiyerarşisi ve Flexbox hizalama teknikleri kullanılarak hazırlanan, temiz ve okunaklı bir makale listeleme arayüzü.",
  slug: "simple-article-listing",
},
{
    position: 8,
    id: "join-our-newsletter",
    title: "Join Our Newsletter",
    difficulty: "Junior",
    status: "done",
    tags: ["Next.js", "Forms", "Validation"],
    description: "Kullanıcı girdilerini kontrol eden, temiz tasarımlı ve özel gölge hiyerarşisine sahip bir bülten kayıt kartı.",
    slug: "join-our-newsletter",
  },
  {
    position: 9,
    id: "simple-faq",
    title: "Simple FAQ",
    difficulty: "Junior",
    status: "done",
    tags: ["Next.js", "Accessibility", "Semantic HTML"],
    description: "Klavye navigasyonu ve semantik etiket kurallarına tam uyumlu, temiz ve okunaklı bir sıkça sorulan sorular sayfası.",
    slug: "simple-faq",
  }
];